### ISSUE TITLE
Micropipenv ignores subdirectory for VCS packages.

### ISSUE THREAD

**Issue by MaxandreOgeret** [thoth-station/micropipenv#236]
**Describe the bug**
Micropipenv ignores subdirectory for VCS packages.

**To Reproduce**
- Generate a Pipenv.lock using git vcs and a subdirectory:
  ```bash
  pipenv install git+ssh://git@github.com/RidgeRun/gstd-1.x.git@v0.13.2#egg=pygstc\&subdirectory=libgstc/python
  ```
- try to run micropipenv
  ```bash
  micropipenv install
  ```

Error : 
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r4wwbzy1/pygstc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r4wwbzy1/pygstc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-r4wwbzy1/pygstc/pip-egg-info
         cwd: /tmp/pip-install-r4wwbzy1/pygstc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-r4wwbzy1/pygstc/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
micropipenv navigates to the subdirectory to find the setup.py

**Screenshots**

**Additional context**

**Comment by frenzymadness** [comment]
Interesting, thanks for the report. Could you please paste the lockfile here?

**Comment by frenzymadness** [comment]
I'm going to open a PR with a fix for this for Pipfile.lock. I wanted to make it work also for poetry, but it seems that [poetry does not support subdirectories](https://github.com/python-poetry/poetry/issues/755) yet.
